regenerated (#2567)
git-svn-id: https://svn.osgeo.org/gdal/trunk/gdal@15474 f0d54148-0727-0410-94bb-9a71ac55c965

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15520,7 +15520,7 @@ fi
 
 
 case "${host_os}" in
-    cygwin* | mingw32* | beos* | darwin*)
+    cygwin* | mingw32* | pw32* | beos* | darwin*)
         ;;
     *)
 
@@ -19540,16 +19540,235 @@ fi
 
 
   if test "$LIBZ_SETTING" = "external" ; then
-    { echo "$as_me:$LINENO: result: using pre-installed libz" >&5
+    { echo "$as_me:$LINENO: checking for inflateCopy in -lz" >&5
+echo $ECHO_N "checking for inflateCopy in -lz... $ECHO_C" >&6; }
+if test "${ac_cv_lib_z_inflateCopy+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lz  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char inflateCopy ();
+int
+main ()
+{
+return inflateCopy ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_z_inflateCopy=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_z_inflateCopy=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_z_inflateCopy" >&5
+echo "${ECHO_T}$ac_cv_lib_z_inflateCopy" >&6; }
+if test $ac_cv_lib_z_inflateCopy = yes; then
+  LIBZ_SETTING=external
+else
+  LIBZ_SETTING=internal
+fi
+
+    if test "$LIBZ_SETTING" = "external" ; then
+        { echo "$as_me:$LINENO: result: using pre-installed libz" >&5
 echo "${ECHO_T}using pre-installed libz" >&6; }
+    else
+        { echo "$as_me:$LINENO: result: using internal libz code as inflateCopy is missing" >&5
+echo "${ECHO_T}using internal libz code as inflateCopy is missing" >&6; }
+    fi
+  else
+    { echo "$as_me:$LINENO: result: using internal libz code as deflateInit_ is missing" >&5
+echo "${ECHO_T}using internal libz code as deflateInit_ is missing" >&6; }
   fi
 
 elif test "$with_libz" != "no" -a "$with_libz" != "internal" ; then
 
   LIBS="-L$with_libz -L$with_libz/lib $LIBS"
+
+  { echo "$as_me:$LINENO: checking for deflateInit_ in -lz" >&5
+echo $ECHO_N "checking for deflateInit_ in -lz... $ECHO_C" >&6; }
+if test "${ac_cv_lib_z_deflateInit_+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lz -L$with_libz -L$with_libz/lib -lz $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char deflateInit_ ();
+int
+main ()
+{
+return deflateInit_ ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_z_deflateInit_=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_z_deflateInit_=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_z_deflateInit_" >&5
+echo "${ECHO_T}$ac_cv_lib_z_deflateInit_" >&6; }
+if test $ac_cv_lib_z_deflateInit_ = yes; then
   LIBZ_SETTING=external
-  { echo "$as_me:$LINENO: result: using libz library from $with_libz" >&5
+else
+  LIBZ_SETTING=internal
+fi
+
+  if test "$LIBZ_SETTING" = "external" ; then
+    { echo "$as_me:$LINENO: checking for inflateCopy in -lz" >&5
+echo $ECHO_N "checking for inflateCopy in -lz... $ECHO_C" >&6; }
+if test "${ac_cv_lib_z_inflateCopy+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lz -L$with_libz -L$with_libz/lib -lz $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char inflateCopy ();
+int
+main ()
+{
+return inflateCopy ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_z_inflateCopy=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_z_inflateCopy=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_z_inflateCopy" >&5
+echo "${ECHO_T}$ac_cv_lib_z_inflateCopy" >&6; }
+if test $ac_cv_lib_z_inflateCopy = yes; then
+  LIBZ_SETTING=external
+else
+  LIBZ_SETTING=internal
+fi
+
+     if test "$LIBZ_SETTING" = "external" ; then
+        { echo "$as_me:$LINENO: result: using libz library from $with_libz" >&5
 echo "${ECHO_T}using libz library from $with_libz" >&6; }
+    else
+        { echo "$as_me:$LINENO: result: using internal libz code as inflateCopy from $with_libz is missing" >&5
+echo "${ECHO_T}using internal libz code as inflateCopy from $with_libz is missing" >&6; }
+    fi
+  else
+    { echo "$as_me:$LINENO: result: using internal libz code as deflateInit_ from $with_libz is missing" >&5
+echo "${ECHO_T}using internal libz code as deflateInit_ from $with_libz is missing" >&6; }
+  fi
 
 fi
 
@@ -25129,10 +25348,6 @@ echo "$as_me: WARNING: Can not find SQLITE_VERSION macro in sqlite3.h header to 
 
 
 
-        cat >>confdefs.h <<\_ACEOF
-#define HAVE_SQLITE3 1
-_ACEOF
-
 
     else
         { echo "$as_me:$LINENO: result: disabled" >&5
@@ -26712,15 +26927,18 @@ fi
 EXTRA_INCLUDES=$EXTRA_INCLUDES
 
 
-if test -f /bin/true.exe ; then
-  EXE_EXT=.exe
-  SO_EXT=dll
-else
-  EXE_EXT=
-fi
-export EXE_EXT
+case "${host_os}" in
+    cygwin* | mingw32* | pw32*)
+      EXE_EXT=.exe
+      SO_EXT=dll
+      ;;
+    *)
+      EXE_EXT=
+      SO_EXT=
+      ;;
+esac
 
-EXE_EXT=$EXE_EXT
+
 
 
 BINTRUE=/bin/true
