regenerated
git-svn-id: https://svn.osgeo.org/gdal/trunk/gdal@12083 f0d54148-0727-0410-94bb-9a71ac55c965

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -458,7 +458,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX CXX_WFLAGS C_WFLAGS AS ac_ct_AS DLLTOOL ac_ct_DLLTOOL OBJDUMP ac_ct_OBJDUMP LIBTOOL SED EGREP FGREP GREP LD DUMPBIN ac_ct_DUMPBIN NM LN_S AR ac_ct_AR STRIP ac_ct_STRIP RANLIB ac_ct_RANLIB lt_ECHO CPP CXXCPP CXX_PIC C_PIC LD_SHARED SO_EXT HAVE_LIBTOOL LIBZ_SETTING PG_CONFIG HAVE_PG PG_INC PG_LIB GRASS_SETTING GRASS_INCLUDE GRASS_GISBASE HAVE_GRASS FITS_SETTING PCRASTER_SETTING NETCDF_SETTING PNG_SETTING TIFF_SETTING TIFF_OPTS GEOTIFF_SETTING JPEG_SETTING GIF_SETTING HAVE_OGDI OGDI_INCLUDE X_FME_HOME HAVE_HDF4 HDF4_INCLUDE HAVE_HDF5 HDF5_INCLUDE HAVE_JASPER JASPER_FLAGS ECW_SETTING KAKDIR HAVE_MRSID MRSID_INCLUDE MRSID_FLAGS OPT_GDAL_FORMATS OGR_ENABLED MYSQL_CONFIG HAVE_MYSQL MYSQL_INC MYSQL_LIB HAVE_XERCES XERCES_INCLUDE ODBC_SETTING ORACLE_OCI_VERSION ORACLE_OCI_CFLAGS ORACLE_OCI_LDFLAGS HAVE_OCI OCI_INCLUDE DODS_INC LIBCURL_CONFIG CURL_SETTING CURL_INC CURL_LIB SQLITE_INC HAVE_SQLITE DWG_PLT DWGDIRECT HAVE_PANORAMA PANORAMA_INC HAVE_IDB IDB_INC IDB_LIB SDE_ENABLED SDE_INC SDE_LIB GEOS_LIBS GEOS_CFLAGS HAVE_GEOS GEOS_VERSION GEOS_CONFIG PROJ_STATIC PROJ_INCLUDE GDAL_VERSION_MAJOR GDAL_VERSION_MINOR GDAL_VERSION_REV GDAL_VER MACOSX_FRAMEWORK EXTRA_INCLUDES EXE_EXT BINTRUE PY_HAVE_SETUPTOOLS BINDINGS PYTHON pythondir pyexecdir pymoddir PYTHON_INCLUDES PYTHON_CC PYTHON_OPT PYTHON_SO PYTHON_CFLAGS PYTHON_LIBS PYTHON_LINK PY_LD_SHARED PY_SO_EXT PYTHON_DEV HAVE_NUMPY NUMPY_FLAG LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX CXX_WFLAGS C_WFLAGS AS ac_ct_AS DLLTOOL ac_ct_DLLTOOL OBJDUMP ac_ct_OBJDUMP LIBTOOL SED EGREP FGREP GREP LD DUMPBIN ac_ct_DUMPBIN NM LN_S AR ac_ct_AR STRIP ac_ct_STRIP RANLIB ac_ct_RANLIB lt_ECHO CPP CXXCPP CXX_PIC C_PIC LD_SHARED SO_EXT HAVE_LIBTOOL LIBZ_SETTING PG_CONFIG HAVE_PG PG_INC PG_LIB GRASS_SETTING GRASS_INCLUDE GRASS_GISBASE HAVE_GRASS FITS_SETTING PCRASTER_SETTING NETCDF_SETTING PNG_SETTING TIFF_SETTING TIFF_OPTS GEOTIFF_SETTING JPEG_SETTING GIF_SETTING HAVE_OGDI OGDI_INCLUDE X_FME_HOME HAVE_HDF4 HDF4_INCLUDE HAVE_HDF5 HDF5_INCLUDE HAVE_JASPER JASPER_FLAGS ECW_SETTING KAKDIR HAVE_MRSID MRSID_INCLUDE MRSID_FLAGS OPT_GDAL_FORMATS OGR_ENABLED MYSQL_CONFIG HAVE_MYSQL MYSQL_INC MYSQL_LIB HAVE_XERCES XERCES_INCLUDE HAVE_EXPAT EXPAT_INCLUDE ODBC_SETTING ORACLE_OCI_VERSION ORACLE_OCI_CFLAGS ORACLE_OCI_LDFLAGS HAVE_OCI OCI_INCLUDE DODS_INC LIBCURL_CONFIG CURL_SETTING CURL_INC CURL_LIB SQLITE_INC HAVE_SQLITE DWG_PLT DWGDIRECT HAVE_PANORAMA PANORAMA_INC HAVE_IDB IDB_INC IDB_LIB SDE_ENABLED SDE_INC SDE_LIB GEOS_LIBS GEOS_CFLAGS HAVE_GEOS GEOS_VERSION GEOS_CONFIG PROJ_STATIC PROJ_INCLUDE GDAL_VERSION_MAJOR GDAL_VERSION_MINOR GDAL_VERSION_REV GDAL_VER MACOSX_FRAMEWORK EXTRA_INCLUDES EXE_EXT BINTRUE PY_HAVE_SETUPTOOLS BINDINGS PYTHON pythondir pyexecdir pymoddir PYTHON_INCLUDES PYTHON_CC PYTHON_OPT PYTHON_SO PYTHON_CFLAGS PYTHON_LIBS PYTHON_LINK PY_LD_SHARED PY_SO_EXT PYTHON_DEV HAVE_NUMPY NUMPY_FLAG LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1053,6 +1053,9 @@ Optional Packages:
   --with-xerces-inc=dir Xerces C++ include directory
   --with-xerces-lib=opts Xerces C++ link option(s)
                              ie. -L/usr/local/lib -lxerces-c1_6_0 -lpthread
+  --with-expat=ARG      Include Expat support (for KML driver)
+  --with-expat-inc=ARG  Expat include directory
+  --with-expat-lib=ARG  Expat link option(s)
   --with-odbc=ARG       Include ODBC support (ARG=no or path)
   --with-oci=[ARG]  use Oracle OCI API from given Oracle home
                           (ARG=path); use existing ORACLE_HOME (ARG=yes);
@@ -4979,13 +4982,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4982: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4985: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4985: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4988: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4988: output\"" >&5)
+  (eval echo "\"\$as_me:4991: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -6034,7 +6037,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6037 "configure"' > conftest.$ac_ext
+  echo '#line 6040 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7717,11 +7720,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7720: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7723: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7724: \$? = $ac_status" >&5
+   echo "$as_me:7727: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8039,11 +8042,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8042: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8045: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8046: \$? = $ac_status" >&5
+   echo "$as_me:8049: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8144,11 +8147,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8147: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8150: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8151: \$? = $ac_status" >&5
+   echo "$as_me:8154: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8199,11 +8202,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8202: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8205: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8206: \$? = $ac_status" >&5
+   echo "$as_me:8209: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10989,7 +10992,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10992 "configure"
+#line 10995 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11089,7 +11092,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11092 "configure"
+#line 11095 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13119,11 +13122,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13122: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13125: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13126: \$? = $ac_status" >&5
+   echo "$as_me:13129: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13218,11 +13221,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13221: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13224: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13225: \$? = $ac_status" >&5
+   echo "$as_me:13228: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13270,11 +13273,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13273: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13276: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13277: \$? = $ac_status" >&5
+   echo "$as_me:13280: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22305,6 +22308,23 @@ else
     HAVE_XERCES=yes
     echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
+
+    # Detecting Xerces version
+    xerces_major=`cat $with_xerces_inc/xercesc/util/XercesVersion.hpp | \
+                    grep '^#define.*XERCES_VERSION_MAJOR.*[0-9]$' | \
+                    sed -e 's/#define XERCES_VERSION_MAJOR.//'`
+
+    xerces_minor=`cat $with_xerces_inc/xercesc/util/XercesVersion.hpp | \
+                    grep '^#define.*XERCES_VERSION_MINOR.*[0-9]$' | \
+                    sed -e 's/#define XERCES_VERSION_MINOR.//'`
+
+    xerces_revision=`cat $with_xerces_inc/xercesc/util/XercesVersion.hpp | \
+                    grep '^#define.*XERCES_VERSION_REVISION.*[0-9]$' | \
+                    sed -e 's/#define XERCES_VERSION_REVISION.//'`
+    XERCES_VERSION="$xerces_major.$xerces_minor.$xerces_revision"
+
+    { echo "$as_me:$LINENO: Xerces $XERCES_VERSION has been found" >&5
+echo "$as_me: Xerces $XERCES_VERSION has been found" >&6;}
   else
     echo "$as_me:$LINENO: result: requested, but compile or link fails!" >&5
 echo "${ECHO_T}requested, but compile or link fails!" >&6
@@ -22328,6 +22348,92 @@ fi
 HAVE_XERCES=$HAVE_XERCES
 
 XERCES_INCLUDE=$XERCES_INCLUDE
+
+
+
+HAVE_EXPAT=no
+
+echo "$as_me:$LINENO: checking for Expat C++" >&5
+echo $ECHO_N "checking for Expat C++... $ECHO_C" >&6
+
+
+# Check whether --with-expat or --without-expat was given.
+if test "${with_expat+set}" = set; then
+  withval="$with_expat"
+
+fi;
+
+# Check whether --with-expat_inc or --without-expat_inc was given.
+if test "${with_expat_inc+set}" = set; then
+  withval="$with_expat_inc"
+
+fi;
+
+# Check whether --with-expat_lib or --without-expat_lib was given.
+if test "${with_expat_lib+set}" = set; then
+  withval="$with_expat_lib"
+
+fi;
+
+if test "$with_expat" = "" -o "$with_expat" = "no" ; then
+
+  echo "$as_me:$LINENO: result: disabled" >&5
+echo "${ECHO_T}disabled" >&6
+
+else
+
+  if test "$with_expat" = "yes" ; then
+    if test -f /usr/local/include/expat.h; then
+      with_expat=/usr/local
+    else
+      with_expat=/usr
+    fi
+  fi
+
+  if test "$with_expat_lib" != "" ; then
+    LIBS="$with_expat_lib $LIBS"
+  else
+    LIBS="-L$with_expat/lib -lexpat $LIBS"
+  fi
+
+  if test "$with_expat_inc" != "" ; then
+    EXPAT_INCLUDE="-I$with_expat_inc"
+  else
+    EXPAT_INCLUDE="-I$with_expat/include"
+  fi
+
+  echo '#include <expat.h>' >> conftest.cpp
+  echo 'int main() {  XML_Parser p = XML_ParserCreate(NULL); XML_ParserFree(p); }' >> conftest.cpp
+  CMD="${CXX} ${EXPAT_INCLUDE} ${CPPFLAGS} -o conftest conftest.cpp $LIBS"
+
+  if test -z "`$CMD 2>&1 | grep -v warning | grep -v skipping`" ; then
+    HAVE_EXPAT=yes
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  else
+    echo "$as_me:$LINENO: result: requested, but compile or link fails!" >&5
+echo "${ECHO_T}requested, but compile or link fails!" >&6
+
+    echo
+    echo $CMD
+    echo
+    $CMD
+    echo
+    echo cat conftest.cpp
+    cat conftest.cpp
+
+    { { echo "$as_me:$LINENO: error: Please correct Expat options, or don't enable Expat." >&5
+echo "$as_me: error: Please correct Expat options, or don't enable Expat." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  rm -f conftest*
+
+fi
+
+HAVE_EXPAT=$HAVE_EXPAT
+
+EXPAT_INCLUDE=$EXTRA_INCLUDES
+
 
 
 
@@ -26121,6 +26227,8 @@ s,@MYSQL_INC@,$MYSQL_INC,;t t
 s,@MYSQL_LIB@,$MYSQL_LIB,;t t
 s,@HAVE_XERCES@,$HAVE_XERCES,;t t
 s,@XERCES_INCLUDE@,$XERCES_INCLUDE,;t t
+s,@HAVE_EXPAT@,$HAVE_EXPAT,;t t
+s,@EXPAT_INCLUDE@,$EXPAT_INCLUDE,;t t
 s,@ODBC_SETTING@,$ODBC_SETTING,;t t
 s,@ORACLE_OCI_VERSION@,$ORACLE_OCI_VERSION,;t t
 s,@ORACLE_OCI_CFLAGS@,$ORACLE_OCI_CFLAGS,;t t
@@ -27608,6 +27716,9 @@ echo "  MySQL support:             ${HAVE_MYSQL}"
 
 
 echo "  XERCES support:            ${HAVE_XERCES}"
+
+
+echo "  Expat support:             ${HAVE_EXPAT}"
 
 
 echo "  ODBC support:              ${ODBC_SETTING}"
