Tom Russo's latest patch for geotiff finding (bug 1344)
git-svn-id: https://svn.osgeo.org/gdal/trunk@10532 f0d54148-0727-0410-94bb-9a71ac55c965

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23375,7 +23375,7 @@ else
 
   GEOTIFF_SETTING=external
 
-    echo "$as_me:$LINENO: checking for XTIFFClientOpen in -lgeotiff" >&5
+      echo "$as_me:$LINENO: checking for XTIFFClientOpen in -lgeotiff" >&5
 echo $ECHO_N "checking for XTIFFClientOpen in -lgeotiff... $ECHO_C" >&6
 if test "${ac_cv_lib_geotiff_XTIFFClientOpen+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -23442,18 +23442,92 @@ echo "${ECHO_T}$ac_cv_lib_geotiff_XTIFFClientOpen" >&6
 if test $ac_cv_lib_geotiff_XTIFFClientOpen = yes; then
   GEOTIFF_SETTING=external
 else
+  GEOTIFF_SETTING=not_found
+fi
+
+
+  if test $GEOTIFF_SETTING = "external" ; then
+    LIBS="-L$with_geotiff/lib -lgeotiff $LIBS"
+    if test  -d $with_geotiff/include ; then
+      EXTRA_INCLUDES="-I$with_geotiff/include $EXTRA_INCLUDES"
+    fi
+  else
+        echo "$as_me:$LINENO: checking for XTIFFClientOpen in -lgeotiff" >&5
+echo $ECHO_N "checking for XTIFFClientOpen in -lgeotiff... $ECHO_C" >&6
+if test "${ac_cv_lib_geotiff_XTIFFClientOpen+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgeotiff -L$with_geotiff $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char XTIFFClientOpen ();
+int
+main ()
+{
+XTIFFClientOpen ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_geotiff_XTIFFClientOpen=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_geotiff_XTIFFClientOpen=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_geotiff_XTIFFClientOpen" >&5
+echo "${ECHO_T}$ac_cv_lib_geotiff_XTIFFClientOpen" >&6
+if test $ac_cv_lib_geotiff_XTIFFClientOpen = yes; then
+  GEOTIFF_SETTING=external
+else
   { { echo "$as_me:$LINENO: error: We require at least GeoTIFF 1.2.1. Consider using the one supplied with GDAL" >&5
 echo "$as_me: error: We require at least GeoTIFF 1.2.1. Consider using the one supplied with GDAL" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-
-  if test -r $with_geotiff/lib/libgeotiff.a ; then
-    LIBS="-L$with_geotiff/lib -lgeotiff $LIBS"
-    EXTRA_INCLUDES="-I$with_geotiff/include $EXTRA_INCLUDES"
-  else
-    LIBS="-L$with_geotiff/lib -lgeotiff $LIBS"
-    EXTRA_INCLUDES="-I$with_geotiff/include $EXTRA_INCLUDES"
+    if test $GEOTIFF_SETTING = "external" ; then
+      LIBS="-L$with_geotiff -lgeotiff $LIBS"
+      EXTRA_INCLUDES="-I$with_geotiff $EXTRA_INCLUDES"
+    fi
   fi
 
   echo "using libgeotiff from $with_geotiff."
