added NAS driver config support
git-svn-id: https://svn.osgeo.org/gdal/trunk@14250 f0d54148-0727-0410-94bb-9a71ac55c965

diff --git a/gdal/configure b/gdal/configure
--- a/gdal/configure
+++ b/gdal/configure
@@ -893,6 +893,7 @@ XERCES_LDFLAGS
 XERCES_VERSION
 HAVE_XERCES
 XERCES_INCLUDE
+HAVE_NAS
 EXPAT_CFLAGS
 EXPAT_LDFLAGS
 EXPAT_VERSION
@@ -5828,13 +5829,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5831: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5832: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5834: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5835: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5837: output\"" >&5)
+  (eval echo "\"\$as_me:5838: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -6931,7 +6932,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6934 "configure"' > conftest.$ac_ext
+  echo '#line 6935 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8622,11 +8623,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8625: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8626: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8629: \$? = $ac_status" >&5
+   echo "$as_me:8630: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8944,11 +8945,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8947: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8948: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8951: \$? = $ac_status" >&5
+   echo "$as_me:8952: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9049,11 +9050,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9052: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9053: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9056: \$? = $ac_status" >&5
+   echo "$as_me:9057: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9104,11 +9105,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9107: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9108: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9111: \$? = $ac_status" >&5
+   echo "$as_me:9112: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11864,7 +11865,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11867 "configure"
+#line 11868 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11964,7 +11965,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11967 "configure"
+#line 11968 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13992,11 +13993,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13995: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13996: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13999: \$? = $ac_status" >&5
+   echo "$as_me:14000: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14091,11 +14092,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14094: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14095: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14098: \$? = $ac_status" >&5
+   echo "$as_me:14099: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14143,11 +14144,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14146: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14147: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14150: \$? = $ac_status" >&5
+   echo "$as_me:14151: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22059,7 +22060,7 @@ if test "${with_hdf4+set}" = set; then
 fi
 
 
-if test "$with_hdf4" = "no" -o "x$with_hdf4" = "x" ; then
+if test x"$with_hdf4" = x"no" ; then
 
   HAVE_HDF4=no
 
@@ -22067,13 +22068,13 @@ if test "$with_hdf4" = "no" -o "x$with_hdf4" = "x" ; then
 
 else
 
-  if test "$with_hdf4" = "yes" -o "$with_hdf4" = "" ; then
+  if test x"$with_hdf4" = x"yes" -o x"$with_hdf4" = x"" ; then
     HDF_LIB_DIR=""
   else
     if test -d $with_hdf4/lib ; then
-      HDF_LIB_DIR=$with_hdf4/lib
+      HDF_LIB_DIR="$with_hdf4/lib"
     else
-      HDF_LIB_DIR=$with_hdf4
+      HDF_LIB_DIR="$with_hdf4"
     fi
   fi
 
@@ -22148,6 +22149,7 @@ else
 fi
 
   if test "$HDF_LIB_NAME" = "missing" ; then
+    unset ac_cv_lib_mfhdf_SDreaddata
     { echo "$as_me:$LINENO: checking for SDreaddata in -lhdf4" >&5
 echo $ECHO_N "checking for SDreaddata in -lhdf4... $ECHO_C" >&6; }
 if test "${ac_cv_lib_hdf4_SDreaddata+set}" = set; then
@@ -22359,27 +22361,37 @@ fi
 
   fi
 
-  if test "$HDF_LIB_NAME" = "missing" -a "$with_hdf4" != "" ; then
-    { { echo "$as_me:$LINENO: error: HDF4 support requested with arg \"$with_hdf4\", but neither hdf4 nor mfhdf lib found" >&5
+  if test "$HDF_LIB_NAME" != "missing" ; then
+
+    LIBS="-L$HDF_LIB_DIR $HDF_LIB_NAME $ORIG_LIBS"
+
+      if test "$with_hdf4" = "yes" -o "$with_hdf4" = "" -a -r /usr/include/hdf/hdf.h ; then
+      HDF4_INCLUDE="-I/usr/include/hdf"
+    elif test -r "$with_hdf4/hdf/hdf.h" ; then
+      HDF4_INCLUDE="-I$with_hdf4/hdf"
+    elif test -r "$with_hdf4/include/hdf/hdf.h" ; then
+      HDF4_INCLUDE="-I$with_hdf4/include/hdf"
+    elif test -r "$with_hdf4/include/hdf.h" ; then
+      HDF4_INCLUDE="-I$with_hdf4/include"
+    elif test -r "$with_hdf4/hdf.h" ; then
+      HDF4_INCLUDE="-I$with_hdf4"
+    fi
+
+    HAVE_HDF4=yes
+
+  else
+
+    if x"$with_hdf4" != x"" ; then
+      { { echo "$as_me:$LINENO: error: HDF4 support requested with arg \"$with_hdf4\", but neither hdf4 nor mfhdf lib found" >&5
 echo "$as_me: error: HDF4 support requested with arg \"$with_hdf4\", but neither hdf4 nor mfhdf lib found" >&2;}
    { (exit 1); exit 1; }; }
+    else
+      LIBS="$ORIG_LIBS"
+      HAVE_HDF4=no
+    fi
+
   fi
 
-  LIBS="-L$HDF_LIB_DIR $HDF_LIB_NAME $ORIG_LIBS"
-
-  if test "$with_hdf4" = "yes" -o "$with_hdf4" = "" -a -r /usr/include/hdf/hdf.h ; then
-    HDF4_INCLUDE="-I/usr/include/hdf"
-  elif test -r "$with_hdf4/hdf/hdf.h" ; then
-    HDF4_INCLUDE="-I$with_hdf4/hdf"
-  elif test -r "$with_hdf4/include/hdf/hdf.h" ; then
-    HDF4_INCLUDE="-I$with_hdf4/include/hdf"
-  elif test -r "$with_hdf4/include/hdf.h" ; then
-    HDF4_INCLUDE="-I$with_hdf4/include"
-  elif test -r "$with_hdf4/hdf.h" ; then
-    HDF4_INCLUDE="-I$with_hdf4"
-  fi
-
-  HAVE_HDF4=yes
 fi
 
 HAVE_HDF4=$HAVE_HDF4
@@ -23820,6 +23832,15 @@ fi
 HAVE_XERCES=$HAVE_XERCES
 
 XERCES_INCLUDE=$XERCES_CFLAGS
+
+
+
+if test "$HAVE_XERCES" = "yes" -a -d ogr/ogrsf_frmts/nas ; then
+  HAVE_NAS=yes
+else
+  HAVE_NAS=no
+fi
+HAVE_NAS=$HAVE_NAS
 
 
 
@@ -28195,6 +28216,7 @@ XERCES_LDFLAGS!$XERCES_LDFLAGS$ac_delim
 XERCES_VERSION!$XERCES_VERSION$ac_delim
 HAVE_XERCES!$HAVE_XERCES$ac_delim
 XERCES_INCLUDE!$XERCES_INCLUDE$ac_delim
+HAVE_NAS!$HAVE_NAS$ac_delim
 EXPAT_CFLAGS!$EXPAT_CFLAGS$ac_delim
 EXPAT_LDFLAGS!$EXPAT_LDFLAGS$ac_delim
 EXPAT_VERSION!$EXPAT_VERSION$ac_delim
@@ -28257,7 +28279,6 @@ PYTHON_LIBS!$PYTHON_LIBS$ac_delim
 PYTHON_LINK!$PYTHON_LINK$ac_delim
 PY_LD_SHARED!$PY_LD_SHARED$ac_delim
 PY_SO_EXT!$PY_SO_EXT$ac_delim
-PYTHON_DEV!$PYTHON_DEV$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -28299,6 +28320,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+PYTHON_DEV!$PYTHON_DEV$ac_delim
 HAVE_NUMPY!$HAVE_NUMPY$ac_delim
 NUMPY_FLAG!$NUMPY_FLAG$ac_delim
 HAVE_OGPYTHON!$HAVE_OGPYTHON$ac_delim
@@ -28306,7 +28328,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 5; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 6; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -29559,6 +29581,9 @@ echo "  Ingres support:            ${HAVE_INGRES}"
 
 
 echo "  Xerces-C support:          ${HAVE_XERCES}"
+
+
+echo "  NAS support:               ${HAVE_NAS}"
 
 
 echo "  Expat support:             ${HAVE_EXPAT}"
