fix up some HDF4 cruft in the HDF5 configure logic
git-svn-id: https://svn.osgeo.org/gdal/trunk@15123 f0d54148-0727-0410-94bb-9a71ac55c965

diff --git a/gdal/configure b/gdal/configure
--- a/gdal/configure
+++ b/gdal/configure
@@ -22588,9 +22588,9 @@ else
 fi
 
 
-  if test "$HDF_LIB_NAME" = "missing" ; then
-    { { echo "$as_me:$LINENO: error: HDF4 support requested with arg $with_hdf4, but neither hdf4 nor mfhdf lib found" >&5
-echo "$as_me: error: HDF4 support requested with arg $with_hdf4, but neither hdf4 nor mfhdf lib found" >&2;}
+  if test "$HDF5_LIB_NAME" = "missing" ; then
+    { { echo "$as_me:$LINENO: error: HDF5 support requested with arg $with_hdf5, but no hdf5 lib found" >&5
+echo "$as_me: error: HDF5 support requested with arg $with_hdf5, but no hdf5 lib found" >&2;}
    { (exit 1); exit 1; }; }
   fi
 
