regnerate autoconf due to previous commit

diff --git a/gdal/configure b/gdal/configure
--- a/gdal/configure
+++ b/gdal/configure
@@ -713,6 +713,8 @@ HAVE_LIBXML2
 LIBXML2_LIBS
 LIBXML2_CFLAGS
 DODS_INC
+LIBDAP_LIBS
+LIBDAP_CFLAGS
 OCI_INCLUDE
 HAVE_OCI
 ODBC_SETTING
@@ -1253,6 +1255,8 @@ OPENJPEG_CFLAGS
 OPENJPEG_LIBS
 LIBKML_CFLAGS
 LIBKML_LIBS
+LIBDAP_CFLAGS
+LIBDAP_LIBS
 LIBXML2_CFLAGS
 LIBXML2_LIBS
 POPPLER_CFLAGS
@@ -2271,6 +2275,9 @@ Some influential environment variables:
   LIBKML_CFLAGS
               C compiler flags for LIBKML, overriding pkg-config
   LIBKML_LIBS linker flags for LIBKML, overriding pkg-config
+  LIBDAP_CFLAGS
+              C compiler flags for LIBDAP, overriding pkg-config
+  LIBDAP_LIBS linker flags for LIBDAP, overriding pkg-config
   LIBXML2_CFLAGS
               C compiler flags for LIBXML2, overriding pkg-config
   LIBXML2_LIBS
@@ -37457,34 +37464,226 @@ else
 $as_echo "libdap $LIBDAP_VER" >&6; }
     else
 
-                        rm -f islibdappost310.*
-        echo '#include "Connect.h"' > islibdappost310.cpp
-        echo 'int main(int argc, char** argv) { return 0; } ' >> islibdappost310.cpp
-        if test -z "`${CXX} ${CXXFLAGS} ${CPPFLAGS} islibdappost310.cpp -c ${DODS_INC} ${CPPFLAGS} 2>&1`" ; then
-                    DODS_INC="$DODS_INC -DLIBDAP_310 -DLIBDAP_39"
-            { $as_echo "$as_me:${as_lineno-$LINENO}: result: libdap >= 3.10" >&5
-$as_echo "libdap >= 3.10" >&6; }
+
+if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
+	if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}pkg-config", so it can be a program name with args.
+set dummy ${ac_tool_prefix}pkg-config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_path_PKG_CONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $PKG_CONFIG" >&5
+$as_echo "$PKG_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+fi
+if test -z "$ac_cv_path_PKG_CONFIG"; then
+  ac_pt_PKG_CONFIG=$PKG_CONFIG
+  # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_path_ac_pt_PKG_CONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  case $ac_pt_PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ac_pt_PKG_CONFIG="$ac_pt_PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_ac_pt_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+ac_pt_PKG_CONFIG=$ac_cv_path_ac_pt_PKG_CONFIG
+if test -n "$ac_pt_PKG_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_pt_PKG_CONFIG" >&5
+$as_echo "$ac_pt_PKG_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+  if test "x$ac_pt_PKG_CONFIG" = x; then
+    PKG_CONFIG=""
+  else
+    case $cross_compiling:$ac_tool_warned in
+yes:)
+{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: using cross tools not prefixed with host triplet" >&5
+$as_echo "$as_me: WARNING: using cross tools not prefixed with host triplet" >&2;}
+ac_tool_warned=yes ;;
+esac
+    PKG_CONFIG=$ac_pt_PKG_CONFIG
+  fi
+else
+  PKG_CONFIG="$ac_cv_path_PKG_CONFIG"
+fi
+
+fi
+if test -n "$PKG_CONFIG"; then
+	_pkg_min_version=0.21
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: checking pkg-config is at least version $_pkg_min_version" >&5
+$as_echo_n "checking pkg-config is at least version $_pkg_min_version... " >&6; }
+	if $PKG_CONFIG --atleast-pkgconfig-version $_pkg_min_version; then
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	else
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+		PKG_CONFIG=""
+	fi
+
+fi
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for LIBDAP" >&5
+$as_echo_n "checking for LIBDAP... " >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$LIBDAP_CFLAGS"; then
+        pkg_cv_LIBDAP_CFLAGS="$LIBDAP_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libdap\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libdap") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_LIBDAP_CFLAGS=`$PKG_CONFIG --cflags "libdap" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$LIBDAP_LIBS"; then
+        pkg_cv_LIBDAP_LIBS="$LIBDAP_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libdap\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libdap") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_LIBDAP_LIBS=`$PKG_CONFIG --libs "libdap" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        LIBDAP_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libdap"`
         else
-            { $as_echo "$as_me:${as_lineno-$LINENO}: result: libdap < 3.10" >&5
+	        LIBDAP_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libdap"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$LIBDAP_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+                HAVE_LIBDAP=no
+elif test $pkg_failed = untried; then
+	HAVE_LIBDAP=no
+else
+	LIBDAP_CFLAGS=$pkg_cv_LIBDAP_CFLAGS
+	LIBDAP_LIBS=$pkg_cv_LIBDAP_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	HAVE_LIBDAP=yes
+fi
+
+        if test "${HAVE_LIBDAP}" = "yes"; then
+                        DODS_INC="$DODS_INC $LIBDAP_CFLAGS -DLIBDAP_310 -DLIBDAP_39"
+        else
+
+                                    rm -f islibdappost310.*
+            echo '#include "Connect.h"' > islibdappost310.cpp
+            echo 'int main(int argc, char** argv) { return 0; } ' >> islibdappost310.cpp
+            if test -z "`${CXX} ${CXXFLAGS} ${CPPFLAGS} islibdappost310.cpp -c ${DODS_INC} ${CPPFLAGS} 2>&1`" ; then
+                            DODS_INC="$DODS_INC -DLIBDAP_310 -DLIBDAP_39"
+                { $as_echo "$as_me:${as_lineno-$LINENO}: result: libdap >= 3.10" >&5
+$as_echo "libdap >= 3.10" >&6; }
+            else
+                { $as_echo "$as_me:${as_lineno-$LINENO}: result: libdap < 3.10" >&5
 $as_echo "libdap < 3.10" >&6; }
 
-                                                rm -f islibdappre39.*
-            echo '#include "DAS.h"' > islibdappre39.cpp
-            echo '#include "AttrTable.h"' >> islibdappre39.cpp
-            echo 'using namespace libdap;' >> islibdappre39.cpp
-            echo 'int main(int argc, char** argv) { DAS oDAS; AttrTable& oAttrTable = oDAS; } ' >> islibdappre39.cpp
-            if test -z "`${CXX} ${CXXFLAGS} ${CPPFLAGS} islibdappre39.cpp -c ${DODS_INC} 2>&1`" ; then
-                            { $as_echo "$as_me:${as_lineno-$LINENO}: result: libdap < 3.9" >&5
+                                                                rm -f islibdappre39.*
+                echo '#include "DAS.h"' > islibdappre39.cpp
+                echo '#include "AttrTable.h"' >> islibdappre39.cpp
+                echo 'using namespace libdap;' >> islibdappre39.cpp
+                echo 'int main(int argc, char** argv) { DAS oDAS; AttrTable& oAttrTable = oDAS; } ' >> islibdappre39.cpp
+                if test -z "`${CXX} ${CXXFLAGS} ${CPPFLAGS} islibdappre39.cpp -c ${DODS_INC} 2>&1`" ; then
+                                    { $as_echo "$as_me:${as_lineno-$LINENO}: result: libdap < 3.9" >&5
 $as_echo "libdap < 3.9" >&6; }
-            else
-                DODS_INC="$DODS_INC -DLIBDAP_39"
-                { $as_echo "$as_me:${as_lineno-$LINENO}: result: libdap >= 3.9" >&5
+                else
+                    DODS_INC="$DODS_INC -DLIBDAP_39"
+                    { $as_echo "$as_me:${as_lineno-$LINENO}: result: libdap >= 3.9" >&5
 $as_echo "libdap >= 3.9" >&6; }
-            fi
-            rm -f islibdappre39.*
+                fi
+                rm -f islibdappre39.*
 
+            fi
+            rm -f islibdappost310.*
         fi
-        rm -f islibdappost310.*
     fi
 
 
@@ -37492,6 +37691,8 @@ $as_echo "libdap >= 3.9" >&6; }
             LIBS="$LIBS `$DODS_BIN/opendap-config --libs`"
     elif test -x $DODS_BIN/dap-config ; then
             LIBS="$LIBS `$DODS_BIN/dap-config --libs`"
+    elif test "${HAVE_LIBDAP}" = "yes"; then
+      LIBS="$LIBS $LIBDAP_LIBS"
     else
             LIBS="$LIBS -L$DODS_LIB -ldap++ -lpthread -lrx"
 
