Add (*nix) support for linking against libspatialite to benefit from spatial functions in SQL queries (#2666)
git-svn-id: https://svn.osgeo.org/gdal/trunk@17083 f0d54148-0727-0410-94bb-9a71ac55c965

diff --git a/gdal/configure b/gdal/configure
--- a/gdal/configure
+++ b/gdal/configure
@@ -908,6 +908,7 @@ LIBCURL_CONFIG
 CURL_SETTING
 CURL_INC
 CURL_LIB
+HAVE_SPATIALITE
 SQLITE3_VERSION
 SQLITE3_CFLAGS
 SQLITE3_LDFLAGS
@@ -1608,6 +1609,7 @@ Optional Packages:
   --with-odbc=ARG       Include ODBC support (ARG=no or path)
   --with-dods-root=ARG  Include DODS support (ARG=no or absolute path)
   --with-curl=ARG       Include curl (ARG=path to curl-config.)
+  --with-spatialite=ARG Include SpatiaLite support (ARG=no or path)
   --with-sqlite3=[ARG]    use SQLite 3 library [default=yes], optionally
                           specify the prefix for sqlite3 library
   --with-dwgdirect=path Include DWG direct support
@@ -5781,13 +5783,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5784: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5786: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5787: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5789: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5790: output\"" >&5)
+  (eval echo "\"\$as_me:5792: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -6884,7 +6886,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6887 "configure"' > conftest.$ac_ext
+  echo '#line 6889 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8575,11 +8577,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8578: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8580: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8582: \$? = $ac_status" >&5
+   echo "$as_me:8584: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8897,11 +8899,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8900: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8902: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8904: \$? = $ac_status" >&5
+   echo "$as_me:8906: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9002,11 +9004,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9005: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9007: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9009: \$? = $ac_status" >&5
+   echo "$as_me:9011: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9057,11 +9059,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9060: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9062: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9064: \$? = $ac_status" >&5
+   echo "$as_me:9066: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11817,7 +11819,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11820 "configure"
+#line 11822 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11917,7 +11919,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11920 "configure"
+#line 11922 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13945,11 +13947,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13948: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13950: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13952: \$? = $ac_status" >&5
+   echo "$as_me:13954: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14044,11 +14046,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14047: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14049: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14051: \$? = $ac_status" >&5
+   echo "$as_me:14053: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14096,11 +14098,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14099: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14101: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14103: \$? = $ac_status" >&5
+   echo "$as_me:14105: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -25475,7 +25477,112 @@ CURL_LIB=$CURL_LIB
 
 
 
-SQLITE3_REQ_VERSION="3.0.0"
+
+# Check whether --with-spatialite was given.
+if test "${with_spatialite+set}" = set; then
+  withval=$with_spatialite;
+fi
+
+
+if test -z "$with_spatialite" -o "$with_spatialite" = "no"; then
+    { echo "$as_me:$LINENO: result: disabled" >&5
+echo "${ECHO_T}disabled" >&6; }
+    HAVE_SPATIALITE=no
+else
+    { echo "$as_me:$LINENO: checking for SpatiaLite" >&5
+echo $ECHO_N "checking for SpatiaLite... $ECHO_C" >&6; }
+    { echo "$as_me:$LINENO: checking for spatialite_init in -lspatialite" >&5
+echo $ECHO_N "checking for spatialite_init in -lspatialite... $ECHO_C" >&6; }
+if test "${ac_cv_lib_spatialite_spatialite_init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lspatialite -L$with_spatialite/lib -lspatialite $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char spatialite_init ();
+int
+main ()
+{
+return spatialite_init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_spatialite_spatialite_init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_spatialite_spatialite_init=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_spatialite_spatialite_init" >&5
+echo "${ECHO_T}$ac_cv_lib_spatialite_spatialite_init" >&6; }
+if test $ac_cv_lib_spatialite_spatialite_init = yes; then
+  SPATIALITE_INIT_FOUND=yes
+else
+  SPATIALITE_INIT_FOUND=no
+fi
+
+    if test -f "$with_spatialite/include/spatialite.h" -a \
+        -f "$with_spatialite/include/spatialite/sqlite3.h" -a \
+        "$SPATIALITE_INIT_FOUND" = "yes"; then
+
+        { echo "$as_me:$LINENO: result: enabled" >&5
+echo "${ECHO_T}enabled" >&6; }
+        HAVE_SPATIALITE=yes
+
+        # SpatiaLite availability implies SQLite availability
+        SQLITE3_CFLAGS="-I$with_spatialite/include -I$with_spatialite/include/spatialite"
+        LIBS="$LIBS -L$with_spatialite/lib -lspatialite"
+        HAVE_SQLITE3=yes
+    else
+        { echo "$as_me:$LINENO: result: disabled" >&5
+echo "${ECHO_T}disabled" >&6; }
+        HAVE_SPATIALITE=no
+    fi
+fi
+
+HAVE_SPATIALITE=$HAVE_SPATIALITE
+
+
+
+if test "${HAVE_SPATIALITE}" = "no" ; then
+    SQLITE3_REQ_VERSION="3.0.0"
 
 
 # Check whether --with-sqlite3 was given.
@@ -25648,8 +25755,9 @@ echo "${ECHO_T}disabled" >&6; }
     fi
 
 
-if test "$HAVE_SQLITE3" = "yes"; then
-    LIBS="$SQLITE3_LDFLAGS $LIBS"
+    if test "$HAVE_SQLITE3" = "yes"; then
+        LIBS="$SQLITE3_LDFLAGS $LIBS"
+    fi
 fi
 
 SQLITE_INC=$SQLITE3_CFLAGS
@@ -25657,6 +25765,7 @@ SQLITE_INC=$SQLITE3_CFLAGS
 HAVE_SQLITE=$HAVE_SQLITE3
 
 HAVE_SQLITE=$HAVE_SQLITE3
+
 
 
 DWGDIRECT=
@@ -28810,6 +28919,7 @@ LIBCURL_CONFIG!$LIBCURL_CONFIG$ac_delim
 CURL_SETTING!$CURL_SETTING$ac_delim
 CURL_INC!$CURL_INC$ac_delim
 CURL_LIB!$CURL_LIB$ac_delim
+HAVE_SPATIALITE!$HAVE_SPATIALITE$ac_delim
 SQLITE3_VERSION!$SQLITE3_VERSION$ac_delim
 SQLITE3_CFLAGS!$SQLITE3_CFLAGS$ac_delim
 SQLITE3_LDFLAGS!$SQLITE3_LDFLAGS$ac_delim
@@ -28857,7 +28967,6 @@ PY_SO_EXT!$PY_SO_EXT$ac_delim
 PYTHON_DEV!$PYTHON_DEV$ac_delim
 HAVE_NUMPY!$HAVE_NUMPY$ac_delim
 NUMPY_FLAG!$NUMPY_FLAG$ac_delim
-HAVE_OGPYTHON!$HAVE_OGPYTHON$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -28899,11 +29008,12 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+HAVE_OGPYTHON!$HAVE_OGPYTHON$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 2; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 3; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -30186,6 +30296,9 @@ echo "  DODS support:              ${HAVE_DODS}"
 
 
 echo "  SQLite support:            ${HAVE_SQLITE}"
+
+
+echo "  SpatiaLite support:        ${HAVE_SPATIALITE}"
 
 
 echo "  DWGdirect support          ${HAVE_DWGDIRECT}"
