Poppler: revision version management. Drop support for ancient versions older than 0.23.0 (preparation for support of newer version: refs #1207, #1208)

diff --git a/gdal/configure b/gdal/configure
--- a/gdal/configure
+++ b/gdal/configure
@@ -668,14 +668,11 @@ PODOFO_PLUGIN_LIB
 PODOFO_INC
 HAVE_PODOFO
 POPPLER_PLUGIN_LIB
-POPPLER_INC
-POPPLER_0_69_OR_LATER
-POPPLER_0_58_OR_LATER
-POPPLER_0_23_OR_LATER
-POPPLER_0_20_OR_LATER
-POPPLER_BASE_STREAM_HAS_TWO_ARGS
-POPPLER_HAS_OPTCONTENT
+POPPLER_MINOR_VERSION
+POPPLER_MAJOR_VERSION
 HAVE_POPPLER
+POPPLER_LIBS
+POPPLER_CFLAGS
 PDF_PLUGIN
 PAM_SETTING
 JSON_INCLUDE
@@ -1111,7 +1108,9 @@ HDF5_LIBS
 OPENJPEG_CFLAGS
 OPENJPEG_LIBS
 LIBKML_CFLAGS
-LIBKML_LIBS'
+LIBKML_LIBS
+POPPLER_CFLAGS
+POPPLER_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1916,6 +1915,10 @@ Some influential environment variables:
   LIBKML_CFLAGS
               C compiler flags for LIBKML, overriding pkg-config
   LIBKML_LIBS linker flags for LIBKML, overriding pkg-config
+  POPPLER_CFLAGS
+              C compiler flags for POPPLER, overriding pkg-config
+  POPPLER_LIBS
+              linker flags for POPPLER, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -34835,208 +34838,225 @@ fi
 
 
 HAVE_POPPLER=no
-POPPLER_HAS_OPTCONTENT=no
-POPPLER_BASE_STREAM_HAS_TWO_ARGS=no
-POPPLER_0_20_OR_LATER=no
-POPPLER_0_23_OR_LATER=no
-POPPLER_0_58_OR_LATER=no
-POPPLER_0_69_OR_LATER=no
+POPPLER_MAJOR_VERSION=
+POPPLER_MINOR_VERSION=
 
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for poppler" >&5
 $as_echo_n "checking for poppler... " >&6; }
 
 if test "$with_poppler" != "no" -a "$with_poppler" != ""; then
 
-    if test "$with_poppler" = "yes" ; then
-        TEST_POPPLER_INC="-I/usr/include -I/usr/include/poppler"
-        TEST_POPPLER_LIB="-lpoppler"
+
+
+if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
+	if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}pkg-config", so it can be a program name with args.
+set dummy ${ac_tool_prefix}pkg-config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_path_PKG_CONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $PKG_CONFIG" >&5
+$as_echo "$PKG_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+fi
+if test -z "$ac_cv_path_PKG_CONFIG"; then
+  ac_pt_PKG_CONFIG=$PKG_CONFIG
+  # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_path_ac_pt_PKG_CONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  case $ac_pt_PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ac_pt_PKG_CONFIG="$ac_pt_PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_ac_pt_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+ac_pt_PKG_CONFIG=$ac_cv_path_ac_pt_PKG_CONFIG
+if test -n "$ac_pt_PKG_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_pt_PKG_CONFIG" >&5
+$as_echo "$ac_pt_PKG_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+  if test "x$ac_pt_PKG_CONFIG" = x; then
+    PKG_CONFIG=""
+  else
+    case $cross_compiling:$ac_tool_warned in
+yes:)
+{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: using cross tools not prefixed with host triplet" >&5
+$as_echo "$as_me: WARNING: using cross tools not prefixed with host triplet" >&2;}
+ac_tool_warned=yes ;;
+esac
+    PKG_CONFIG=$ac_pt_PKG_CONFIG
+  fi
+else
+  PKG_CONFIG="$ac_cv_path_PKG_CONFIG"
+fi
+
+fi
+if test -n "$PKG_CONFIG"; then
+	_pkg_min_version=0.21
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: checking pkg-config is at least version $_pkg_min_version" >&5
+$as_echo_n "checking pkg-config is at least version $_pkg_min_version... " >&6; }
+	if $PKG_CONFIG --atleast-pkgconfig-version $_pkg_min_version; then
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	else
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+		PKG_CONFIG=""
+	fi
+
+fi
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for POPPLER" >&5
+$as_echo_n "checking for POPPLER... " >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$POPPLER_CFLAGS"; then
+        pkg_cv_POPPLER_CFLAGS="$POPPLER_CFLAGS"
     else
-        TEST_POPPLER_INC="-I$with_poppler/include -I$with_poppler/include/poppler"
-        TEST_POPPLER_LIB="-L$with_poppler/lib -lpoppler"
+        if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"poppler >= 0.23.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "poppler >= 0.23.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_POPPLER_CFLAGS=`$PKG_CONFIG --cflags "poppler >= 0.23.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
     fi
-
-    # Check that we can accept Page::pageObj private member
-    rm -f testpoppler.*
-    echo '#define private public' > testpoppler.cpp
-    echo '#include <poppler/Page.h>' >> testpoppler.cpp
-    echo '#include <poppler/splash/SplashBitmap.h>' >> testpoppler.cpp
-    echo 'int main(int argc, char** argv) { return &(((Page*)0x8000)->pageObj) == 0; } ' >> testpoppler.cpp
-
-    if test -z "`${CXX} ${CXXFLAGS} ${CPPFLAGS} testpoppler.cpp -o testpoppler ${TEST_POPPLER_INC} ${TEST_POPPLER_LIB} 2>&1`" ; then
-        HAVE_POPPLER=yes
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$POPPLER_LIBS"; then
+        pkg_cv_POPPLER_LIBS="$POPPLER_LIBS"
     else
-        # poppler 0.23.0 needs to be linked against pthread
-        TEST_POPPLER_LIB="${TEST_POPPLER_LIB} -lpthread"
-        if test -z "`${CXX} ${CXXFLAGS} ${CPPFLAGS} testpoppler.cpp -o testpoppler ${TEST_POPPLER_INC} ${TEST_POPPLER_LIB} 2>&1`" ; then
-            HAVE_POPPLER=yes
-        fi
+        if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"poppler >= 0.23.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "poppler >= 0.23.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_POPPLER_LIBS=`$PKG_CONFIG --libs "poppler >= 0.23.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
     fi
+else
+	pkg_failed=untried
+fi
 
-    if test "$HAVE_POPPLER" = "yes"; then
-        if test "$PDF_PLUGIN" = "no"; then
-            LIBS="${TEST_POPPLER_LIB} ${LIBS}"
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        POPPLER_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "poppler >= 0.23.0"`
+        else
+	        POPPLER_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "poppler >= 0.23.0"`
         fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$POPPLER_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+                POPPLER_VERSION=
+elif test $pkg_failed = untried; then
+	POPPLER_VERSION=
+else
+	POPPLER_CFLAGS=$pkg_cv_POPPLER_CFLAGS
+	POPPLER_LIBS=$pkg_cv_POPPLER_LIBS
         { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 $as_echo "yes" >&6; }
-        POPPLER_INC=$TEST_POPPLER_INC
-        POPPLER_PLUGIN_LIB="${TEST_POPPLER_LIB}"
-
-        CHECK_OTHER_POPPLER_VERSION=yes
-
-        if test "$CHECK_OTHER_POPPLER_VERSION" = "yes"; then
-            { $as_echo "$as_me:${as_lineno-$LINENO}: checking if OptionalContent has API >= 0.69.0" >&5
-$as_echo_n "checking if OptionalContent has API >= 0.69.0... " >&6; }
-            rm -f testpoppler.*
-            echo '#include <poppler/OptionalContent.h>' > testpoppler.cpp
-            echo 'int main(int argc, char** argv) {' >> testpoppler.cpp
-            echo 'OCGs ocg(nullptr, nullptr);' >> testpoppler.cpp
-            echo 'ocg.getOCGs().size();' >> testpoppler.cpp
-            echo 'return 0; }' >> testpoppler.cpp
-            if test -z "`${CXX} ${CXXFLAGS} ${CPPFLAGS} testpoppler.cpp -c ${POPPLER_INC} 2>&1`" ; then
-                POPPLER_0_69_OR_LATER=yes
-                POPPLER_0_58_OR_LATER=yes
-                POPPLER_0_23_OR_LATER=yes
-                POPPLER_0_20_OR_LATER=yes
-                POPPLER_BASE_STREAM_HAS_TWO_ARGS=yes
-                POPPLER_HAS_OPTCONTENT=yes
-                CHECK_OTHER_POPPLER_VERSION=no
-                { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
-$as_echo "yes" >&6; }
-            else
-                { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
-$as_echo "no" >&6; }
-            fi
-        fi
-
-        if test "$CHECK_OTHER_POPPLER_VERSION" = "yes"; then
-            # And now we check if we have Poppler >= 0.58.0
-            { $as_echo "$as_me:${as_lineno-$LINENO}: checking if Object does have new API (>= 0.58.0)" >&5
-$as_echo_n "checking if Object does have new API (>= 0.58.0)... " >&6; }
-            rm -f testpoppler.*
-            echo '#include <poppler/Object.h>' > testpoppler.cpp
-            echo 'int main(int argc, char** argv) { Object o(objNull); return 0; }' >> testpoppler.cpp
-            if test -z "`${CXX} ${CXXFLAGS} ${CPPFLAGS} testpoppler.cpp -c ${POPPLER_INC} 2>&1`" ; then
-                POPPLER_0_58_OR_LATER=yes
-                POPPLER_0_23_OR_LATER=yes
-                POPPLER_0_20_OR_LATER=yes
-                POPPLER_BASE_STREAM_HAS_TWO_ARGS=yes
-                POPPLER_HAS_OPTCONTENT=yes
-                CHECK_OTHER_POPPLER_VERSION=no
-                { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
-$as_echo "yes" >&6; }
-            else
-                { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
-$as_echo "no" >&6; }
-            fi
-        fi
-
-        if test "$CHECK_OTHER_POPPLER_VERSION" = "yes"; then
-
-            # And now try another dirty thing, but this one is
-            # optional.
-            { $as_echo "$as_me:${as_lineno-$LINENO}: checking if Catalog::optContent exists" >&5
-$as_echo_n "checking if Catalog::optContent exists... " >&6; }
-            rm -f testpoppler.*
-            echo '#define private public' > testpoppler.cpp
-            echo '#include <poppler/Object.h>' >> testpoppler.cpp
-            echo '#include <poppler/Catalog.h>' >> testpoppler.cpp
-            echo 'int main(int argc, char** argv) { return &(((Catalog*)0x8000)->optContent) == 0; }' >> testpoppler.cpp
-            if test -z "`${CXX} ${CXXFLAGS} ${CPPFLAGS} testpoppler.cpp -c ${POPPLER_INC} 2>&1`" ; then
-                POPPLER_HAS_OPTCONTENT=yes
-                { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
-$as_echo "yes" >&6; }
-            else
-                { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
-$as_echo "no" >&6; }
-            fi
-
-            # And now we check if we have Poppler >= 0.16.0
-            { $as_echo "$as_me:${as_lineno-$LINENO}: checking if BaseStream constructor needs 2 arguments" >&5
-$as_echo_n "checking if BaseStream constructor needs 2 arguments... " >&6; }
-            rm -f testpoppler.*
-            echo '#include <poppler/Object.h>' > testpoppler.cpp
-            echo '#include <poppler/Stream.h>' >> testpoppler.cpp
-            echo 'class TestStream: public BaseStream {' >> testpoppler.cpp
-            echo 'public:' >> testpoppler.cpp
-            echo '  TestStream() : BaseStream(0,0) {}' >> testpoppler.cpp
-            echo '};' >> testpoppler.cpp
-            echo 'int main(int argc, char** argv) { return 0; }' >> testpoppler.cpp
-            if test -z "`${CXX} ${CXXFLAGS} ${CPPFLAGS} testpoppler.cpp -c ${POPPLER_INC} 2>&1`" ; then
-                POPPLER_BASE_STREAM_HAS_TWO_ARGS=yes
-                { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
-$as_echo "yes" >&6; }
-
-                # And now we check if we have Poppler >= 0.20.0
-                { $as_echo "$as_me:${as_lineno-$LINENO}: checking if we have Poppler >= 0.20.0" >&5
-$as_echo_n "checking if we have Poppler >= 0.20.0... " >&6; }
-                rm -f testpoppler.*
-                echo '#include <poppler/Error.h>' > testpoppler.cpp
-                echo 'int main(int argc, char** argv) { setErrorCallback(0,0); return 0; }' >> testpoppler.cpp
-                if test -z "`${CXX} ${CXXFLAGS} ${CPPFLAGS} testpoppler.cpp -c ${POPPLER_INC} 2>&1`" ; then
-                    POPPLER_0_20_OR_LATER=yes
-                    { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
-$as_echo "yes" >&6; }
-
-                    # And now we check if we have Poppler >= 0.23.0
-                    { $as_echo "$as_me:${as_lineno-$LINENO}: checking if we have Poppler >= 0.23.0" >&5
-$as_echo_n "checking if we have Poppler >= 0.23.0... " >&6; }
-                    rm -f testpoppler.*
-                    echo '#include <poppler/Object.h>' > testpoppler.cpp
-                    echo '#include <poppler/Stream.h>' >> testpoppler.cpp
-                    echo 'class TestStream: public BaseStream {' >> testpoppler.cpp
-                    echo 'public:' >> testpoppler.cpp
-                    echo '  TestStream() : BaseStream(0,0) {}' >> testpoppler.cpp
-                    echo '  ~TestStream() {}' >> testpoppler.cpp
-                    echo '  virtual BaseStream *copy() { return BaseStream::copy(); }' >> testpoppler.cpp
-                    echo '};' >> testpoppler.cpp
-                    echo 'int main(int argc, char** argv) { return 0; }' >> testpoppler.cpp
-                    if test -z "`${CXX} ${CXXFLAGS} ${CPPFLAGS} testpoppler.cpp -c ${POPPLER_INC} 2>&1`" ; then
-                        POPPLER_0_23_OR_LATER=yes
-                        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
-$as_echo "yes" >&6; }
-                    else
-                        { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
-$as_echo "no" >&6; }
-                    fi
-
-                else
-                    { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
-$as_echo "no" >&6; }
-                fi
-
-            else
-                { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
-$as_echo "no" >&6; }
-            fi
-        fi
-    else
-        { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
-$as_echo "no" >&6; }
+	POPPLER_VERSION=`$PKG_CONFIG --modversion poppler`
+fi
+    if test "$POPPLER_VERSION" != ""; then
+        HAVE_POPPLER=yes
+        POPPLER_MAJOR_VERSION=`expr $POPPLER_VERSION : '\([0-9]*\)'`
+        POPPLER_MINOR_VERSION=`expr $POPPLER_VERSION : '[0-9]*\.\([0-9]*\)'`
+        POPPLER_CFLAGS=`echo $POPPLER_CFLAGS $POPPLER_CFLAGS | sed "s/include\/poppler/include/"`
     fi
-    rm -f testpoppler.*
-    rm -f testpoppler
 else
     { $as_echo "$as_me:${as_lineno-$LINENO}: result: disabled" >&5
 $as_echo "disabled" >&6; }
 fi
 
+if test "$HAVE_POPPLER" = "yes" -a "$PDF_PLUGIN" = "no"; then
+    LIBS="${POPPLER_LIBS} ${LIBS}"
+fi
+
 HAVE_POPPLER=$HAVE_POPPLER
 
-POPPLER_HAS_OPTCONTENT=$POPPLER_HAS_OPTCONTENT
+POPPLER_MAJOR_VERSION=$POPPLER_MAJOR_VERSION
 
-POPPLER_BASE_STREAM_HAS_TWO_ARGS=$POPPLER_BASE_STREAM_HAS_TWO_ARGS
+POPPLER_MINOR_VERSION=$POPPLER_MINOR_VERSION
 
-POPPLER_0_20_OR_LATER=$POPPLER_0_20_OR_LATER
+POPPLER_CFLAGS=$POPPLER_CFLAGS
 
-POPPLER_0_23_OR_LATER=$POPPLER_0_23_OR_LATER
-
-POPPLER_0_58_OR_LATER=$POPPLER_0_58_OR_LATER
-
-POPPLER_0_69_OR_LATER=$POPPLER_0_69_OR_LATER
-
-POPPLER_INC=$POPPLER_INC
-
-POPPLER_PLUGIN_LIB=$POPPLER_PLUGIN_LIB
+POPPLER_PLUGIN_LIB=$POPPLER_LIBS
 
 
 
