regenerated (https://trac.osgeo.org/gdal/ticket/1920)
git-svn-id: https://svn.osgeo.org/gdal/branches/1.4@12528 f0d54148-0727-0410-94bb-9a71ac55c965

diff --git a/gdal/configure b/gdal/configure
--- a/gdal/configure
+++ b/gdal/configure
@@ -23154,7 +23154,76 @@ else
   TIFF_SETTING=internal
 fi
 
-  fi
+        echo "$as_me:$LINENO: checking for TIFFScanlineSize64 in -ltiff" >&5
+echo $ECHO_N "checking for TIFFScanlineSize64 in -ltiff... $ECHO_C" >&6
+if test "${ac_cv_lib_tiff_TIFFScanlineSize64+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ltiff  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char TIFFScanlineSize64 ();
+int
+main ()
+{
+TIFFScanlineSize64 ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_tiff_TIFFScanlineSize64=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_tiff_TIFFScanlineSize64=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_tiff_TIFFScanlineSize64" >&5
+echo "${ECHO_T}$ac_cv_lib_tiff_TIFFScanlineSize64" >&6
+if test $ac_cv_lib_tiff_TIFFScanlineSize64 = yes; then
+  HAVE_BIGTIFF=yes
+else
+  HAVE_BIGTIFF=no
+fi
+
+   fi
 
   if test "$TIFF_SETTING" = "external" ; then
     LIBS="-ltiff $LIBS"
@@ -23181,6 +23250,83 @@ else
   fi
 
   echo "using libtiff from $with_libtiff."
+
+    echo "$as_me:$LINENO: checking for TIFFScanlineSize64 in -ltiff" >&5
+echo $ECHO_N "checking for TIFFScanlineSize64 in -ltiff... $ECHO_C" >&6
+if test "${ac_cv_lib_tiff_TIFFScanlineSize64+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ltiff  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char TIFFScanlineSize64 ();
+int
+main ()
+{
+TIFFScanlineSize64 ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_tiff_TIFFScanlineSize64=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_tiff_TIFFScanlineSize64=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_tiff_TIFFScanlineSize64" >&5
+echo "${ECHO_T}$ac_cv_lib_tiff_TIFFScanlineSize64" >&6
+if test $ac_cv_lib_tiff_TIFFScanlineSize64 = yes; then
+  HAVE_BIGTIFF=yes
+else
+  HAVE_BIGTIFF=no
+fi
+
+
+fi
+
+if test "${HAVE_BIGTIFF}" = "yes" ; then
+  { { echo "$as_me:$LINENO: error: libtiff >= 4.0 is not supported in this version of GDAL ! This will be supported in GDAL >= 1.5.0" >&5
+echo "$as_me: error: libtiff >= 4.0 is not supported in this version of GDAL ! This will be supported in GDAL >= 1.5.0" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 TIFF_SETTING=$TIFF_SETTING
